#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module Thrift
    class User
      include ::Thrift::Struct
      NAME = 1
      ACCOUNT = 2
      URL = 3
      AVATAR_URL = 4

      ::Thrift::Struct.field_accessor self, :name, :account, :url, :avatar_url
      FIELDS = {
        NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
        ACCOUNT => {:type => ::Thrift::Types::STRING, :name => 'account'},
        URL => {:type => ::Thrift::Types::STRING, :name => 'url'},
        AVATAR_URL => {:type => ::Thrift::Types::STRING, :name => 'avatar_url'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class TextComment
      include ::Thrift::Struct
      ID = 1
      TIMESTAMP = 2
      MEDIUM = 3
      TEXT = 4

      ::Thrift::Struct.field_accessor self, :id, :timestamp, :medium, :text
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'},
        TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class ImageComment
      include ::Thrift::Struct
      ID = 1
      TIMESTAMP = 2
      MEDIUM = 3
      IMAGE_URL = 4

      ::Thrift::Struct.field_accessor self, :id, :timestamp, :medium, :image_url
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'},
        IMAGE_URL => {:type => ::Thrift::Types::STRING, :name => 'image_url'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class TextPost
      include ::Thrift::Struct
      ID = 1
      TIMESTAMP = 2
      MEDIUM = 3
      TEXT = 4

      ::Thrift::Struct.field_accessor self, :id, :timestamp, :medium, :text
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'},
        TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class ImagePost
      include ::Thrift::Struct
      ID = 1
      TIMESTAMP = 2
      MEDIUM = 3
      IMAGE_URL = 4

      ::Thrift::Struct.field_accessor self, :id, :timestamp, :medium, :image_url
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'},
        IMAGE_URL => {:type => ::Thrift::Types::STRING, :name => 'image_url'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class CommentPost
      include ::Thrift::Struct
      ID = 1
      TIMESTAMP = 2
      MEDIUM = 3

      ::Thrift::Struct.field_accessor self, :id, :timestamp, :medium
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class Repost
      include ::Thrift::Struct
      ID = 1
      TIMESTAMP = 2
      MEDIUM = 3

      ::Thrift::Struct.field_accessor self, :id, :timestamp, :medium
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

  end
