#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module Thrift
    class User
      include ::Thrift::Struct
      ID = 1
      TYPE = 2
      USERNAME = 3
      URL = 4
      AVATAR_URL = 5

      ::Thrift::Struct.field_accessor self, :id, :type, :username, :url, :avatar_url
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        TYPE => {:type => ::Thrift::Types::STRING, :name => 'type'},
        USERNAME => {:type => ::Thrift::Types::STRING, :name => 'username'},
        URL => {:type => ::Thrift::Types::STRING, :name => 'url'},
        AVATAR_URL => {:type => ::Thrift::Types::STRING, :name => 'avatar_url'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class Comment
      include ::Thrift::Struct
      ID = 1
      CREATED_AT = 2
      FROM = 3
      TEXT = 4

      ::Thrift::Struct.field_accessor self, :id, :created_at, :from, :text
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        CREATED_AT => {:type => ::Thrift::Types::STRING, :name => 'created_at'},
        FROM => {:type => ::Thrift::Types::STRING, :name => 'from'},
        TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class TextPost
      include ::Thrift::Struct
      ID = 1
      CREATED_AT = 2
      FROM = 3
      TEXT = 4

      ::Thrift::Struct.field_accessor self, :id, :created_at, :from, :text
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        CREATED_AT => {:type => ::Thrift::Types::STRING, :name => 'created_at'},
        FROM => {:type => ::Thrift::Types::STRING, :name => 'from'},
        TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class ImagePost
      include ::Thrift::Struct
      ID = 1
      CREATED_AT = 2
      FROM = 3
      IMAGE_URL = 4
      IMAGE_WIDTH = 5
      IMAGE_HEIGHT = 6
      TEXT = 7

      ::Thrift::Struct.field_accessor self, :id, :created_at, :from, :image_url, :image_width, :image_height, :text
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        CREATED_AT => {:type => ::Thrift::Types::STRING, :name => 'created_at'},
        FROM => {:type => ::Thrift::Types::STRING, :name => 'from'},
        IMAGE_URL => {:type => ::Thrift::Types::STRING, :name => 'image_url'},
        IMAGE_WIDTH => {:type => ::Thrift::Types::I32, :name => 'image_width'},
        IMAGE_HEIGHT => {:type => ::Thrift::Types::I32, :name => 'image_height'},
        TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class AudioPost
      include ::Thrift::Struct
      ID = 1
      DATE = 2
      TIMESTAMP = 3
      FROM = 4
      TEXT = 5

      ::Thrift::Struct.field_accessor self, :id, :date, :timestamp, :from, :text
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        DATE => {:type => ::Thrift::Types::STRING, :name => 'date'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        FROM => {:type => ::Thrift::Types::STRING, :name => 'from'},
        TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class AudioMedia
      include ::Thrift::Struct
      ID = 1
      MP3_URL = 2
      OGG_URL = 3

      ::Thrift::Struct.field_accessor self, :id, :mp3_url, :ogg_url
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        MP3_URL => {:type => ::Thrift::Types::STRING, :name => 'mp3_url'},
        OGG_URL => {:type => ::Thrift::Types::STRING, :name => 'ogg_url'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class CommentPost
      include ::Thrift::Struct
      ID = 1
      CREATED_AT = 2
      FROM = 3

      ::Thrift::Struct.field_accessor self, :id, :created_at, :from
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        CREATED_AT => {:type => ::Thrift::Types::STRING, :name => 'created_at'},
        FROM => {:type => ::Thrift::Types::STRING, :name => 'from'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class Repost
      include ::Thrift::Struct
      ID = 1
      DATE = 2
      TIMESTAMP = 3
      MEDIUM = 4

      ::Thrift::Struct.field_accessor self, :id, :date, :timestamp, :medium
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        DATE => {:type => ::Thrift::Types::STRING, :name => 'date'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

  end
