#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module Thrift
    class User
      include ::Thrift::Struct
      USERNAME = 1
      ACCOUNT = 2
      URL = 3
      AVATAR_URL = 4

      ::Thrift::Struct.field_accessor self, :username, :account, :url, :avatar_url
      FIELDS = {
        USERNAME => {:type => ::Thrift::Types::STRING, :name => 'username'},
        ACCOUNT => {:type => ::Thrift::Types::STRING, :name => 'account'},
        URL => {:type => ::Thrift::Types::STRING, :name => 'url'},
        AVATAR_URL => {:type => ::Thrift::Types::STRING, :name => 'avatar_url'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class Comment
      include ::Thrift::Struct
      ID = 1
      DATE = 2
      TIMESTAMP = 3
      MEDIUM = 4
      TEXT = 5

      ::Thrift::Struct.field_accessor self, :id, :date, :timestamp, :medium, :text
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        DATE => {:type => ::Thrift::Types::STRING, :name => 'date'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'},
        TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class TextPost
      include ::Thrift::Struct
      ID = 1
      DATE = 2
      TIMESTAMP = 3
      MEDIUM = 4
      TEXT = 5

      ::Thrift::Struct.field_accessor self, :id, :date, :timestamp, :medium, :text
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        DATE => {:type => ::Thrift::Types::STRING, :name => 'date'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'},
        TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class ImagePost
      include ::Thrift::Struct
      ID = 1
      DATE = 2
      TIMESTAMP = 3
      MEDIUM = 4
      IMAGE_URL = 5
      TEXT = 6

      ::Thrift::Struct.field_accessor self, :id, :date, :timestamp, :medium, :image_url, :text
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        DATE => {:type => ::Thrift::Types::STRING, :name => 'date'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'},
        IMAGE_URL => {:type => ::Thrift::Types::STRING, :name => 'image_url'},
        TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class AudioPost
      include ::Thrift::Struct
      ID = 1
      DATE = 2
      TIMESTAMP = 3
      MEDIUM = 4
      AUDIO_URL = 5
      TEXT = 6

      ::Thrift::Struct.field_accessor self, :id, :date, :timestamp, :medium, :audio_url, :text
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        DATE => {:type => ::Thrift::Types::STRING, :name => 'date'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'},
        AUDIO_URL => {:type => ::Thrift::Types::STRING, :name => 'audio_url'},
        TEXT => {:type => ::Thrift::Types::STRING, :name => 'text'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class CommentPost
      include ::Thrift::Struct
      ID = 1
      DATE = 2
      TIMESTAMP = 3
      MEDIUM = 4

      ::Thrift::Struct.field_accessor self, :id, :date, :timestamp, :medium
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        DATE => {:type => ::Thrift::Types::STRING, :name => 'date'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class Repost
      include ::Thrift::Struct
      ID = 1
      DATE = 2
      TIMESTAMP = 3
      MEDIUM = 4

      ::Thrift::Struct.field_accessor self, :id, :date, :timestamp, :medium
      FIELDS = {
        ID => {:type => ::Thrift::Types::I32, :name => 'id'},
        DATE => {:type => ::Thrift::Types::STRING, :name => 'date'},
        TIMESTAMP => {:type => ::Thrift::Types::I32, :name => 'timestamp'},
        MEDIUM => {:type => ::Thrift::Types::STRING, :name => 'medium'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

  end
